services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-7.0-fpm}
    container_name: ${APP_NAME}-php
    ports:
      - '${FORWARD_HTTP_PORT:-80}:80'
      - '${FORWARD_HTTPS_PORT:-443}:${FORWARD_HTTPS_PORT:-443}'
    volumes:
      - ./src:/var/www/html:delegated
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:10.1
    container_name: ${APP_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_PORT: ${FORWARD_DB_PORT:-3306}:3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8082}:80'
    links:
      - db:db

volumes:
  db_data:

networks:
  default:
    name: ${APP_NAME}-network
